In [7]:
import numpy as np

In [10]:
arr_3d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_3d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
arr_3d.size

12

In [15]:
arr_3d.ndim

2